### ISSUE TITLE
WG scoping options: fixed, incremental improvements, extensible

### ISSUE THREAD

**Issue by anssiko** [w3c/immersive-web-wg-charter#16]
The scope of a WG charter can be worded in various ways. There are at least the following options on how to scope a WG charter that have been used in production. Since the [official guidebook](https://www.w3.org/Guide/process/charter.html) does not talk about this aspect, I thought it might be useful to document the common approaches here for discussion and consideration.

Disclaimer: I don't have any position on which way the IW CG should go about this. I feel the community should have a say here.

### Fixed scope

The group's scope is fixed until the charter end date. This usual model works (surprisingly) if the scope is clear over the chartered period. Not the best fit for early stage work when the scope is not yet fully settled. This makes the charter review easier for the broader membership. Expectation is often that there's a seed specification that explicitly defines the technical scope. Example: [Service Workers WG Charter](https://www.w3.org/2017/08/sw-charter.html).

### Fixed scope with "potential deliverables" option

- A variant of the former. The group's scope is fixed until its charter end date, but includes "potential deliverables" the WG can start to work on during its period with WG consensus. Example: [Web Platform WG Charter](https://www.w3.org/2017/08/webplatform-charter.html).

>The following documents have been identified as potential Recommendation Track deliverables, if there is consensus in the Working Group that they are ready to become Recommendation-track.

### Incorporate incremental improvements to spec revisions

- The group produces revisions to its spec(s), optionally on a predefined cadence, snapshotting changes that have been incrementally adopted by the Working Group from incubation. Example: [WebAssembly WG Charter](https://www.w3.org/2017/08/wasm-charter).

>Revisions will be produced [N times a year], snapshotting changes that have been incrementally adopted by the Working Group [...] Each successive version will incrementally incorporate improvements to support: [enumerate possible features to be incorporated.]

### Extensible charter
- In this option mid-term charter additions are allowed subject to the Advisory Committee and Director approval. Example: [Devices and Sensors WG Charter](https://w3c.github.io/dap-charter/DeviceAPICharter.html).

>If additional in-scope Recommendation-track deliverables need to be added to the Charter before the Charter expires, the Working Group will prepare an updated Charter that differs only in deliverables.

**Comment by TrevorFSmith** [comment]
This is a helpful summary and we'll use it during the conversations about the charter. Thanks, Anssi!

**Comment by himorin** [comment]
(propose to close this issue, which points to the last charter draft but not one under discussion)
