### ISSUE TITLE
comments on 2022 draft charter (2021/Dec/20)

### ISSUE THREAD

**Issue by himorin** [w3c/immersive-web-wg-charter#39]
leaving following comments for future discussion

- WebXR Device API, gamepads module, AR module, hit test module, and anchors module state `We will continue to maintain the XXX but we don’t intend to add new features or make substantial changes.` but not include any text to bring these to REC
  - webxr-ar-module has `unstable` warning, should be removed?
- anchors module has expected completion target as Q2 2022, but it's before FPWD - so almost(?) impossible.
- `face detection` was closed?: https://github.com/immersive-web/proposals/issues/41
- followings are still in CG (just note)
  - Raw camera access
  - navigation
  - Real World Geometry

**Comment by AdaRoseCannon** [comment]
/agenda to go through proposed charter and gather feedback from the community

**Comment by AdaRoseCannon** [comment]
ah damn my bot isn't here

**Comment by himorin** [comment]
(updating initial comment with additional items also)

- webxr-ar-module has unstable warning (at both /TR/ and ED), should we remove this if we state we don't intend to add new features or make substantial changes?

**Comment by himorin** [comment]
Checked bikeshed errors/warnings over all WG specs, and filed PRs (or issues) if any point found.
I've not checked target references are correct. (although I've left a comment in https://github.com/immersive-web/dom-overlays/pull/50 - which are at close position from ones to be fixed.)

**Comment by Yonet** [comment]
@himorin @AdaRoseCannon FYI, I've changed the expected dates to 2022/24, so that we do nothave 2021 or earlier dates left in the draft. For the actual expected dates, I've talked to the editors before the new years and we will be working on updating the dates in the coming weeks. Thanks.

**Comment by AdaRoseCannon** [comment]
Thank you so much @Yonet

**Comment by cperey** [comment]
@AdaRoseCannon On January 11 you asked me to add in the draft charter a section about the external coordination with OGC. I propose to add the following:

<a href="https://www.ogc.org/" target="_blank">Open Geospatial Consortium</a>
          </dt>
          <dd>
            The Open Geospatial Consortium creates free, publicly available geospatial standards that enable new technologies. OGC also manages an agile and collaborative research and development process that anticipates and solves real-world geospatial challenges experienced by its members. One of the OGC working groups that is most relevant for Immersive Web focuses on development of <a href="https://github.com/opengeospatial/GeoPose" target= "_blank">GeoPose,</a> an encoding specification to seamlessly express, record, and share the geographically-anchored position and 6 DOF orientation of objects in an entirely consistent manner across different applications, users, devices, services, and platforms which adopt the standard or are able to translate/exchange the GeoPose into another CRS. The Working Group will coordinate its roadmap with planned evolutions of relevant OGC standards, including but not limited to GeoPose. 
          </dd>
          <dt>

**Comment by Yonet** [comment]
Hi @cperey, I was under the impression that we will add [Spatial Data on the Web Working Group](https://www.w3.org/groups/wg/sdw) in the W3C Groups section. Do you prefer adding Open Geospatial Consortium in the external organizations section instead? Or both?
Thanks!

**Comment by cperey** [comment]
Hi @yonet I believe both OGC and SDW WG should be added, but I didn't realize that they were both actions for me :-)

Here is short text for the SDW WG to be added in W3C Groups section :

> The scope of the [Spatial Data on the Web Working Group (SDWWG)](https://www.w3.org/2021/sdw/) is Web technologies as that may be applied to location. Where relevant it promotes LinkedData using the 5 Stars of Linked Data paradigm but this is not to the exclusion of other technologies. The Spatial Data on the Web WG is part of the W3C Data Activity and is explicitly chartered to work in collaboration with the Open Geospatial Consortium (OGC) as described in Dependencies & Liaisons.

Please let me know if you have any questions.

**Comment by Yonet** [comment]
@cperey I've added OGC under the external groups and geo-alignment repo as one of the potential incubations to our charter proposal. During our WG meeting, you've mentioned "the spatial data on the web group doesn't have time and are not volunteering", so they are not added under the W3C groups section. Once the PR is merged, I will close this issue. Thank you volunteers and for the connection.

**Comment by himorin** [comment]
closing. (PR merged, and all points fixed.)
